### ISSUE TITLE
Achtung

### ISSUE THREAD

**Issue by Piloswine1** [vigoroous/devwebs#1]
https://github.com/vigoroous/devwebs/blob/905ed881d2dbc141764736e0b59a721b0e8b4af3/digipaper/post.php#L3-L13

- [x] Чел фак че по кодировкам?
https://github.com/vigoroous/devwebs/blob/905ed881d2dbc141764736e0b59a721b0e8b4af3/digipaper/post.php#L50-L64

- [ ] Сразу с эндлайном в конце....

**Comment by vigoroous** [comment]
Даа, обосрались малеху)))
